version: "1.0"
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx playwright test
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results
      - ./allure-results/:/app/allure-results
